### ISSUE TITLE
Error in ubuntu 21.04

### ISSUE THREAD

**Issue by arch-user-france1** [ceremcem/on-idle#3]
Here error message if I fire the script: Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":0".

It worked with 20.10
I'm googling it...
It looks weird. Also `xset dpms force off` doesn't work anymore
I think they changed to another module or removed something. Please update your code

**Comment by ceremcem** [comment]
This notification hasn't arrived me, sorry. 

Do you still experience the same issue?

**Comment by arch-user-france1** [comment]
I don't need it anymore but yeah

It doesn't work for Ubuntu 21.04 because some changes I think.

**Comment by arch-user-france1** [comment]
DPMS function also removed

**Comment by ceremcem** [comment]
Okay, I think I should test the `Makefile` on Ubuntu because it still works as intended in Debian Buster.

**Comment by arch-user-france1** [comment]
Debian doesn't use the Ubuntu Gnome
The Display Manager changed how it's operating

**Comment by arch-user-france1** [comment]
Ah.. It works.. Maybe it didn't work on my server because no display server was running lol

**Comment by arch-user-france1** [comment]
yes it works

**Comment by ceremcem** [comment]
Maybe this detail should be added to the Readme.
